name: utoc_webview
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  
