name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app (no code signing)
        run: flutter build ios --release --no-codesign

      - name: Create Payload and IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r utoc-ios.ipa Payload
          rm -rf Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: utoc-ios-ipa
          path: utoc-ios.ipa
